name: "detection"
platform: "onnxruntime_onnx"
max_batch_size: 8  # supports dynamic batching now

input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [3, 640, 640]
  }
]

output [
  { name: "loc", data_type: TYPE_FP32, dims: [-1, 4] },
  { name: "conf", data_type: TYPE_FP32, dims: [-1, 2] },
  { name: "landmarks", data_type: TYPE_FP32, dims: [-1, 10] }
]

dynamic_batching {
  preferred_batch_size: [1, 4, 8, 16]
  max_queue_delay_microseconds: 500
}

instance_group [{ kind: KIND_GPU }]
